CREATE DATABASE Pexeso
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_czech_ci;

USE Pexeso;

CREATE TABLE GameBoards (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Status VARCHAR(250),
  LastMove TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE Cards (
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  GameBoardID INT NOT NULL,
  CardNumber INT DEFAULT 0 NOT NULL,
  Status VARCHAR(250) ,
  CardOrder INT NOT NULL DEFAULT 0,
  CONSTRAINT HerniPlocha_FK FOREIGN KEY (HerniPlochaID) REFERENCES HerniPlochy (ID)
);
